services:
  ui-builder:
    container_name: ui-builder
    build:
      context: .
      dockerfile: Dockerfile.ui-builder
    environment:
      COMMON_UI_BUILD_FOLDER: /ui-build
      IS_BFX_API_STAGING: ${IS_BFX_API_STAGING:-0}
      IS_DEV_ENV: ${IS_DEV_ENV:-0}
      CURRENT_UID: ${CURRENT_UID:-"1000:1000"}
    volumes:
      - ui-build:/ui-build

  linux-builder:
    container_name: linux-builder
    build:
      context: .
      dockerfile: Dockerfile.linux-builder
    environment:
      ELECTRON_CACHE: /root/.cache/electron
      ELECTRON_BUILDER_CACHE: /root/.cache/electron-builder
      COMMON_UI_BUILD_FOLDER: /ui-build
      COMMON_DIST_FOLDER: /dist
      IS_BFX_API_STAGING: ${IS_BFX_API_STAGING:-0}
      IS_DEV_ENV: ${IS_DEV_ENV:-0}
      IS_AUTO_UPDATE_DISABLED: ${IS_AUTO_UPDATE_DISABLED:-0}
      IS_PUBLISHED: ${IS_PUBLISHED:-0}
      GH_TOKEN: ${GH_TOKEN:-}
      GITHUB_TOKEN: ${GITHUB_TOKEN:-}
      REPO_OWNER: ${REPO_OWNER:-}
      EP_GH_IGNORE_TIME: ${EP_GH_IGNORE_TIME:-true}
      CURRENT_UID: ${CURRENT_UID:-"1000:1000"}
    volumes:
      - ui-build:/ui-build
      - ./dist:/dist
      - ~/.cache/electron:/root/.cache/electron
      - ~/.cache/electron-builder:/root/.cache/electron-builder

  win-builder:
    container_name: win-builder
    build:
      context: .
      dockerfile: Dockerfile.win-builder
    environment:
      ELECTRON_CACHE: /root/.cache/electron
      ELECTRON_BUILDER_CACHE: /root/.cache/electron-builder
      COMMON_UI_BUILD_FOLDER: /ui-build
      COMMON_DIST_FOLDER: /dist
      IS_BFX_API_STAGING: ${IS_BFX_API_STAGING:-0}
      IS_DEV_ENV: ${IS_DEV_ENV:-0}
      IS_AUTO_UPDATE_DISABLED: ${IS_AUTO_UPDATE_DISABLED:-0}
      IS_PUBLISHED: ${IS_PUBLISHED:-0}
      GH_TOKEN: ${GH_TOKEN:-}
      GITHUB_TOKEN: ${GITHUB_TOKEN:-}
      REPO_OWNER: ${REPO_OWNER:-}
      EP_GH_IGNORE_TIME: ${EP_GH_IGNORE_TIME:-true}
      CURRENT_UID: ${CURRENT_UID:-"1000:1000"}
    volumes:
      - ui-build:/ui-build
      - ./dist:/dist
      - ~/.cache/electron:/root/.cache/electron
      - ~/.cache/electron-builder:/root/.cache/electron-builder

  mac-builder:
    container_name: mac-builder
    build:
      context: .
      dockerfile: Dockerfile.mac-builder
    environment:
      ELECTRON_CACHE: /root/.cache/electron
      ELECTRON_BUILDER_CACHE: /root/.cache/electron-builder
      COMMON_UI_BUILD_FOLDER: /ui-build
      COMMON_DIST_FOLDER: /dist
      IS_BFX_API_STAGING: ${IS_BFX_API_STAGING:-0}
      IS_DEV_ENV: ${IS_DEV_ENV:-0}
      IS_AUTO_UPDATE_DISABLED: ${IS_AUTO_UPDATE_DISABLED:-0}
      IS_PUBLISHED: ${IS_PUBLISHED:-0}
      GH_TOKEN: ${GH_TOKEN:-}
      GITHUB_TOKEN: ${GITHUB_TOKEN:-}
      REPO_OWNER: ${REPO_OWNER:-}
      EP_GH_IGNORE_TIME: ${EP_GH_IGNORE_TIME:-true}
      CURRENT_UID: ${CURRENT_UID:-"1000:1000"}
    volumes:
      - ui-build:/ui-build
      - ./dist:/dist
      - ~/.cache/electron:/root/.cache/electron
      - ~/.cache/electron-builder:/root/.cache/electron-builder

volumes:
  ui-build:
