name: 'E2E Test Report'
run-name: 'E2E Test Report: Commit ${{ github.sha }}'

on:
  workflow_run:
    workflows: ['Build release']
    types:
      - completed

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  e2e-web-page-report:
    name: E2E Web Page Report
    runs-on: ubuntu-22.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Download Linux E2E test results
      uses: actions/download-artifact@v4
      with:
        run-id: ${{ github.event.workflow_run.id }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        name: linux-e2e-test-results
        path: linux-e2e-test-results
    - uses: dorny/test-reporter@v1.8.0
      id: linux-e2e-test-results
      with:
        name: Linux E2E Tests
        path: linux-e2e-test-results/e2e-test-report.xml
        reporter: jest-junit
        # Workaround for error 'fatal: not a git repository' caused by a call to 'git ls-files'
        # See: https://github.com/dorny/test-reporter/issues/169#issuecomment-1583560458
        max-annotations: 0
    - name: Download Win E2E test results
      uses: actions/download-artifact@v4
      with:
        run-id: ${{ github.event.workflow_run.id }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        name: win-e2e-test-results
        path: win-e2e-test-results
    - uses: dorny/test-reporter@v1.8.0
      id: win-e2e-test-results
      with:
        name: Win E2E Tests
        path: win-e2e-test-results/e2e-test-report.xml
        reporter: jest-junit
        max-annotations: 0
    - name: Download Mac E2E test results
      uses: actions/download-artifact@v4
      with:
        run-id: ${{ github.event.workflow_run.id }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        name: mac-e2e-test-results
        path: mac-e2e-test-results
    - uses: dorny/test-reporter@v1.8.0
      id: mac-e2e-test-results
      with:
        name: Mac E2E Tests
        path: mac-e2e-test-results/e2e-test-report.xml
        reporter: jest-junit
        max-annotations: 0
    - name: E2E Test Report Summary
      run: |
        echo "### E2E Test Report page is ready! :rocket:" >> $GITHUB_STEP_SUMMARY
        echo "And available at the following links for applicable OSs:" >> $GITHUB_STEP_SUMMARY
        echo "- [Linux](${{ steps.linux-e2e-test-results.outputs.url_html }})" >> $GITHUB_STEP_SUMMARY
        echo "- [Win](${{ steps.win-e2e-test-results.outputs.url_html }})" >> $GITHUB_STEP_SUMMARY
        echo "- [Mac](${{ steps.mac-e2e-test-results.outputs.url_html }})" >> $GITHUB_STEP_SUMMARY
